@startuml

title __PATTERN's Class Diagram__\n

  namespace  {
    namespace bserver {
      namespace pattern {
        class observer.pattern.BarChartObserver {
            - courseData : Vector<CourseRecord>
            + BarChartObserver()
            + paint()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace bserver {
      namespace pattern {
        class observer.pattern.CourseController {
            - courseData : CourseData
            - coursePanel : JPanel
            - sliders : Vector<JSlider>
            + CourseController()
            + actionPerformed()
            + addCourse()
            {static} + main()
            + stateChanged()
            + update()
        }
      }
    }
  }
  

  namespace  {
    namespace bserver {
      namespace pattern {
        class observer.pattern.CourseData {
            - courseData : Vector<CourseRecord>
            + CourseData()
            + addCourseRecord()
            + changeCourseRecord()
            + getUpdate()
        }
      }
    }
  }
  

  namespace  {
    namespace bserver {
      namespace pattern {
        abstract class observer.pattern.Observable {
            # observers : Vector<Observer>
            + Observable()
            + attach()
            + detach()
            {abstract} + getUpdate()
            + notifyObservers()
        }
      }
    }
  }
  

  namespace  {
    namespace bserver {
      namespace pattern {
        interface observer.pattern.Observer {
            {abstract} + update()
        }
      }
    }
  }
  

  observer.pattern.BarChartObserver .up.|> Observer
  observer.pattern.CourseController .up.|> ActionListener
  observer.pattern.CourseController .up.|> ChangeListener
  observer.pattern.CourseController .up.|> Observer


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
